/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package conagua.tramites;

import conagua.conexion.Conexion;
import conagua.usuarios.EditarUsuario;
import conagua.usuarios.ListaUsuarios;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author kevin
 */
public class ListaTramites extends javax.swing.JFrame {

    /**
     * Creates new form ListaTramites
     */
    Conexion con;
    DefaultTableModel modelo;
    String columnas[] = {"Codigo", "Nombre"};
    String empty[] = {"Sin resultados"};
    ArrayList<Integer> ids_tramites;
    Object obj;

    public ListaTramites() {
        initComponents();
        this.setLocationRelativeTo(null);
        con = new Conexion();
        this.llenarTabla();

    }

    public void llenarTabla() {
        ids_tramites = new ArrayList<Integer>();
        modelo = new DefaultTableModel(null, columnas);
        String sql = "select * from tramites";
        con.Conectar();
        ResultSet rs = con.Consulta(sql);
        try {
            if (rs.next()) {
                rs.beforeFirst();
                while (rs.next()) {
                    Vector vec = new Vector();
                    ids_tramites.add(rs.getInt("id"));
                    vec.add(rs.getString("codigo"));
                    vec.add(rs.getString("nombre"));
                    modelo.addRow(vec);
                }
                t_tramites.setModel(modelo);
            } else {
                modelo.addRow(empty);
            }
            con.Cerrar();
        } catch (SQLException ex) {
            Logger.getLogger(ListaUsuarios.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public void buscarTramite() {

        ids_tramites = new ArrayList<Integer>();
        modelo = new DefaultTableModel(null, columnas);
        String sql = "select * from tramites where "
                + "nombre like '%" + jb_buscar.getText() + "%' or "
                + "codigo like '%" + jb_buscar.getText() + "%'";

        con.Conectar();
        ResultSet rs = con.Consulta(sql);

        try {
            if (rs.next()) {
                rs.beforeFirst();
                while (rs.next()) {
                    Vector vec = new Vector();
                    vec.add(rs.getString("codigo"));
                    vec.add(rs.getString("nombre"));
                    modelo.addRow(vec);
                }
            } else {
                modelo.addRow(empty);
            }
            t_tramites.setModel(modelo);
            con.Cerrar();
        } catch (SQLException ex) {
            Logger.getLogger(ListaUsuarios.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jb_buscar = new javax.swing.JTextField();
        jb_agregar = new javax.swing.JButton();
        jb_editar = new javax.swing.JButton();
        jb_borrar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        t_tramites = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(633, 287));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 102, 102));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/conagua/imagenes/icons/serach.png"))); // NOI18N
        jLabel2.setText("Buscar");
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        jb_buscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jb_buscarKeyReleased(evt);
            }
        });

        jb_agregar.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 12)); // NOI18N
        jb_agregar.setForeground(new java.awt.Color(102, 102, 102));
        jb_agregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/conagua/imagenes/icons/boton_add.png"))); // NOI18N
        jb_agregar.setText("Agregar");
        jb_agregar.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jb_agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_agregarActionPerformed(evt);
            }
        });

        jb_editar.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 12)); // NOI18N
        jb_editar.setForeground(new java.awt.Color(102, 102, 102));
        jb_editar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/conagua/imagenes/icons/boton_edit.png"))); // NOI18N
        jb_editar.setText("Editar");
        jb_editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_editarActionPerformed(evt);
            }
        });

        jb_borrar.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 12)); // NOI18N
        jb_borrar.setForeground(new java.awt.Color(102, 102, 102));
        jb_borrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/conagua/imagenes/icons/trash.png"))); // NOI18N
        jb_borrar.setText("Borrar");
        jb_borrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_borrarActionPerformed(evt);
            }
        });

        t_tramites.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 12)); // NOI18N
        t_tramites.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        t_tramites.setSelectionBackground(new java.awt.Color(102, 102, 102));
        jScrollPane2.setViewportView(t_tramites);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jb_buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 477, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jb_agregar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jb_editar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jb_borrar, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jb_buscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jb_agregar)
                        .addGap(18, 18, 18)
                        .addComponent(jb_editar)
                        .addGap(18, 18, 18)
                        .addComponent(jb_borrar))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jb_borrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_borrarActionPerformed
        // TODO add your handling code here:

        /*if (t_tramites.getSelectedRow() > -1) {
            try {
                String sql = "update tramites where id=" + ids_tramites.get(t_tramites.getSelectedRow());
                con.Conectar();
                PreparedStatement ps = con.InsertPS(sql);
                ps.setInt(1, 0);
                ps.executeUpdate();
                con.Cerrar();
                JOptionPane.showMessageDialog(null, "Se borro correctamente el tramite", "aviso", JOptionPane.INFORMATION_MESSAGE);
                this.llenarTabla();
            } catch (SQLException ex) {
                Logger.getLogger(ListaTramites.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Seleccione un tramite", "WARNING", JOptionPane.WARNING_MESSAGE);
        }*/
    }//GEN-LAST:event_jb_borrarActionPerformed

    private void jb_editarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_editarActionPerformed
        // TODO add your handling code here:
        if (t_tramites.getSelectedRow() > -1) {
            EditarTramite et = new EditarTramite(this, ids_tramites.get(t_tramites.getSelectedRow()));
            et.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(null, "Seleccione un usuario.", "¡WARNING!", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_jb_editarActionPerformed

    private void jb_agregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_agregarActionPerformed
        // TODO add your handling code here:
        NuevoTramite tramite = new NuevoTramite(this);
        tramite.setVisible(true);
    }//GEN-LAST:event_jb_agregarActionPerformed

    private void jb_buscarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jb_buscarKeyReleased
        // TODO add your handling code here:
        if (!jb_buscar.getText().trim().isEmpty()) {
            buscarTramite();
        } else {
            llenarTabla();
        }
    }//GEN-LAST:event_jb_buscarKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ListaTramites.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ListaTramites.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ListaTramites.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ListaTramites.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ListaTramites().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton jb_agregar;
    private javax.swing.JButton jb_borrar;
    private javax.swing.JTextField jb_buscar;
    private javax.swing.JButton jb_editar;
    private javax.swing.JTable t_tramites;
    // End of variables declaration//GEN-END:variables
}
